patchworkpp_node:
  ros__parameters:
    base_frame: "velodyne"
    sensor_height: 0.86
    num_iter: 3
    num_lpr: 20
    num_min_pts: 0
    th_seeds: 0.25
    th_dist: 0.125
    th_seeds_v: 0.25
    th_dist_v: 0.9
    max_range: 80.0
    min_range: 1.0
    uprightness_thr: 0.101
    verbose: true
