make_bbox:
  ros__parameters:
    input_topic: "/pointcloud/clustered"
    output_topic: "/perception/bboxes"
    marker_topic: "/perception/bboxes_marker"
    sigmoid_k: 0.3
    sigmoid_n_mid: 15.0

    # bbox 크기 상한 필터 (대회 라바콘 규격 + 0.05m 패딩)
    #   라바콘: X=0.500, Y=0.500, Z=0.840

    # 대회 라바콘 규격 :
    #   - 가로(X): 약 0.500 m
    #   - 세로(Y): 약 0.500 m
    #   - 높이(Z): 약 0.840 m
    max_size_x: 0.55
    max_size_y: 0.55
    max_size_z: 0.89
